rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3

env:
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.2.0"

matrix:

notifications:
  recipients:
    - kpumuk@kpumuk.info

addons:
  code_climate:
    repo_token: "8792cbc0d1780830ddd3dd7eb1c25f09f386ba8f04449ad830039469406a6ab3"
